### PR TITLE
Eg 68 fix movelists arrows

### LINKED ISSUE #68: Fix Top-Arrow and Down-Arrow for Move-Lists
## Expected Behavior
What should be happening is that the arrows are placed correctly, and they should appear.

## Actual/Current Behavior
Despite making this work on a different branch, for some reason the arrows are not appearing for the user's Pokemon, but it is appearing on the enemy Pokemon. Although the arrows for the enemy Pokemon does appear, they are not on the right location.

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Added another conditional to render the top and bottom arrows if the user has not select the stats option in SinglePokemon.js.
2. Refactored the conditional renderings for the top and bottom arrows into functions for readability in SinglePokemon.js.
3. Added another conditional to render the top and bottom arrows if the user has not select the stats option in EnemyPokemon.js.
4. Refactored the conditional renderings for the top and bottom arrows into functions for readability in EnemyPokemon.js.

## Purpose
The problem was that the arrows were not at their correct places based on their positioning property, and they were still seen when the user selects an the stats-list option.

## Approach
One way on fixing the arrow placements was to change their positioning property from `fixed` -> `absolute`. Then, place the `span` elements outside the moves-list `div` element since the CSS property of `overflow-y: auto` could interfere with the positioning property, and fix either their `top`, `left`, or `right` CSS properties. Lastly, the conditional renderings for the top and down arrows were hard to read, and thus were reduced into functions for readability.

## Final Note
As final note, the moves-list are used in both SinglePokemon and EnemyPokemon components, and to fix this duplication would be to create a MovesList component. This will be dealth with on Issue #70 .

## Screenshots
review-the-pr-please

Closes #68

### CODE REVIEW

File: pokemon-app/src/components/EnemyPokemon.js [hunk 1]
```diff
@@ -11,6 +11,45 @@ const EnemyPokemon = ({ enemyPokemon, hasEnemy }) => {
...
+  const renderMovesListBottomArrow = () =>
+    // True if the moves property exist in pokemon object.
+    checkDoesMovesKeyExistInObject() &&
+    // True if the moves length is greater than seven.
+    !checkIsMovesListLengthSevenOrLess() &&
+    // True if the scrollbar is not at the bottom.
+    !checkIsScrollbarAtBottom() &&
+    // True if the stats list has not been selected.
+    !checkIsStatsListSelected();
+
```
Comment (Lap343) [inline pokemon-app/src/components/EnemyPokemon.js:52]: dang Elias on a comment spree. Good job

Comment (kmausolf) [inline pokemon-app/src/components/EnemyPokemon.js:52]: Since this is repeated in the SinglePokemon file, it may be better to have the check function take a parameter containing the pokemon to be checked then refactor it out to a utility function.

File: pokemon-app/src/components/SinglePokemon.js [hunk 2]
```diff
@@ -20,6 +20,44 @@ const SinglePokemon = ({
...
+  const renderMovesListBottomArrow = () =>
+    // True if the moves property exist in pokemon object.
+    checkDoesMovesKeyExistInObject() &&
+    // True if the moves length is greater than seven.
+    !checkIsMovesListLengthSevenOrLess() &&
+    // True if the scrollbar is not at the bottom.
+    !checkIsScrollbarAtBottom() &&
+    // True if the stats list has not been selected.
+    !checkIsStatsListSelected();
+
```
Comment (krferrell) [inline pokemon-app/src/components/SinglePokemon.js:60]: This is very clean and easy to read, but is it the same code from EnemyPokemon.js?

**Review by krferrell — APPROVED** [review]
Thanks for writing very readable code! This is looking fantastic.

**Review by Lap343 — APPROVED** [review]
Tons of functions. Tons of comments. Very clean code

File: pokemon-app/src/components/SinglePokemon.js (hunk 2 above)
Comment (BlackCubes) [reply pokemon-app/src/components/SinglePokemon.js:60]: Yas. Ima make moves-list into a component since that is used in both components

File: pokemon-app/src/components/EnemyPokemon.js (hunk 1 above)
Comment (BlackCubes) [reply pokemon-app/src/components/EnemyPokemon.js:52]: Was about to do that, but I'm going to save that for the next issue :)
