### PR TITLE
bug(audio):fix audio inconsistencies bug

### LINKED ISSUE #134: Audio issues with credit screen
## Expected Behavior
Audio should stay muted across all screens when muted by the user.
If the user mutes the sound on the home screen, it should stay muted when you navigate to a different screen.

## Actual/Current Behavior
The audio replays and unmutes when you navigate to and back from the credits screen.

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Had the audio be muted throughout the app if the user presses the mute button.

## Purpose
The app seemed inconsistent with this bug because the audio would play switching from the main screen to the credits screen

## Approach
Have the state of if the music is playing be handled and seen throughout the app

Closes #134

### CODE REVIEW

**Review by Wolftownn — APPROVED** [review]
Nice job finding the solution!

File: pokemon-app/src/components/Main.js [hunk 1]
```diff
@@ -30,10 +30,11 @@ const Main = ({
   friendlyOriginalHP,
   enemyOriginalHP,
   themeSongSource,
+  isPlaying,
+  setIsPlaying
 }) => {
   const [friendlyStatsOnTop, setFriendlyStatsOnTop] = useState(false);
   const [enemyStatsOnTop, setEnemyStatsOnTop] = useState(false);
-  const [isPlaying, setIsPlaying] = useState(true);
```
Comment (BlackCubes) [inline pokemon-app/src/components/Main.js:36]: Good catch!

**Review by BlackCubes — APPROVED** [review]
Good fix on the bug!
