### PR TITLE
fix(type-capitalization): capitalize the type value with the capitali…

### LINKED ISSUE #91: Fix the Capitalization of Single Pokemon Type
## Expected Behavior
In the types display for the single pokemon, the word 'type' should be capitalized.

## Actual/Current Behavior
There is no capitalization on the word 'type' for single pokemon.

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Fix the type value to be capitalized by using the custom `capitalize` utility function.

## Purpose
The type value in `TypeCheck.js` is not capitalize while the other property values are.

## Approach
To capitalize the type value, the simple approach was to use the custom `capitalize` function on it. This leaves a better UI design for the user.

Closes #91

### CODE REVIEW

**Review by Wolftownn — APPROVED** [review]
Noice!

File: pokemon-app/src/components/TypeCheck.js [hunk 1]
```diff
@@ -1,45 +1,47 @@
...
-    return <div className="type-check">
-        <div className="type-title">
-            <div>Type</div>
-            <div>Srong Against</div>
-            <div>Week Against</div>
-            <div>Resistant To</div> 
-            <div>Vulnerable To</div>
-        </div>
-        {typeReturn(type)}
+    typeArray.map((item) => <li key={item}>{item}a</li>);
```
Comment (connielion) [inline pokemon-app/src/components/TypeCheck.js:30]: Interesting...Is `item` unique?

**Review by connielion — APPROVED** [review]
Looks good overall!

File: pokemon-app/src/components/TypeCheck.js (hunk 1 above)
Comment (kmausolf) [reply pokemon-app/src/components/TypeCheck.js:30]: I would rename `item` to `type` so that it's more descriptive.

File: pokemon-app/src/components/TypeCheck.js [hunk 2]
```diff
@@ -1,45 +1,47 @@
...
 
 const TypeCheck = ({ pokemon }) => {
-    let type = []
-    
-    for(let i = 0; i < pokemon.types.length; i++){
-        type.push(pokemon.types[i].type.name)
-    }
+  let type = [];
+
+  for (let i = 0; i < pokemon.types.length; i++) {
```
Comment (krferrell) [inline pokemon-app/src/components/TypeCheck.js:8]: nice space

**Review by krferrell — APPROVED** [review]
Good catch on the capitalization. It is the little things.
